spring.application.name=Drive_Backend

spring.datasource.url=jdbc:mysql://localhost:3306/drive_backend
spring.datasource.username=root
spring.datasource.password=iamgroot

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#file storage path
file.upload-dir=uploads/
